/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_name from './city_name';
import city_pattern from './city_pattern';
import postcode_pattern from './postcode_pattern';
import state from './state';

const location: LocationDefinition = {
  city_name,
  city_pattern,
  postcode_pattern,
  state,
};

export default location;
