name: Integration Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # weekly on Mondays at 03:00

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set node version to 22
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build
        run: pnpm run build

      - name: Integration Test
        run: pnpm run integration-test
