name: PR

on:
  pull_request:
  merge_group:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check-code-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: 'Check Code Generation: node-22, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set node version to 22
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Generate code
        id: generate
        run: |
          pnpm run generate:locales
          pnpm run generate:api-docs
          pnpm run build
          pnpm run test -u
        continue-on-error: true
        env:
          CI_PREFLIGHT: true

      - name: Check diff
        id: diff
        run: |
          git add .
          git diff --cached --name-only | sed -E 's/^(.*)$/::error file=\1,title=Diff detected::Please run `pnpm run preflight` and commit the changes./'
          git diff --cached --name-only --exit-code
        continue-on-error: true

      - name: Status
        if: ${{ steps.generate.outcome == 'failure' || steps.diff.outcome == 'failure' }}
        run: exit 1
